# Project: hello
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = heloWorld.o
LINKOBJ  = heloWorld.o
LIBS     = -L"C:/Users/meire/Dev-Cpp/MinGW64/lib" -L"C:/Users/meire/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/meire/Dev-Cpp/MinGW64/include" -I"C:/Users/meire/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/meire/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/meire/Dev-Cpp/MinGW64/include" -I"C:/Users/meire/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/meire/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/meire/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = hello.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

heloWorld.o: heloWorld.cpp
	$(CPP) -c heloWorld.cpp -o heloWorld.o $(CXXFLAGS)
